# Generated by Django 3.1.2 on 2020-11-30 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
